CREATE DATABASE pizza_company_analysis;
USE pizza_company_analysis;

-- Checking records
SELECT * FROM orders;
SELECT * FROM order_details;
SELECT * FROM pizzas;
SELECT * FROM pizza_types;

-- Null Values
SELECT *
FROM orders
WHERE order_id IS NULL
   OR date IS NULL
   OR time IS NULL;
   
SELECT *
FROM pizza_types
WHERE pizza_type_id IS NULL
   OR name IS NULL
   OR category IS NULL
   OR ingredients IS NULL;

SELECT *
FROM pizzas
WHERE pizza_id IS NULL
   OR pizza_type_id IS NULL
   OR size IS NULL
   OR price IS NULL;

SELECT *
FROM order_details
WHERE order_details_id IS NULL
   OR order_id IS NULL
   OR pizza_id IS NULL
   OR quantity IS NULL;
   
-- Duplicate Values
SELECT order_id, COUNT(*)
FROM orders
GROUP BY order_id
HAVING COUNT(*) > 1;

SELECT pizza_type_id, COUNT(*) 
FROM pizza_types
GROUP BY pizza_type_id
HAVING COUNT(*) > 1;

SELECT pizza_id, COUNT(*)
FROM pizzas
GROUP BY pizza_id
HAVING COUNT(*) > 1;

SELECT order_details_id, COUNT(*) 
FROM order_details
GROUP BY order_details_id
HAVING COUNT(*) > 1;

-- Checking Invalid Values
SELECT *
FROM order_details
WHERE quantity <= 0;

SELECT *
FROM pizza_types
WHERE category = ''
   OR ingredients = '';
   
SELECT *
FROM pizzas
WHERE price <= 0;

SELECT *
FROM pizzas
WHERE size NOT IN ('S', 'M', 'L', 'XL', 'XXL');

-- Sales Performance
-- 1. What is the total revenue generated by the company?
SELECT CAST(SUM(p.price * od.quantity) AS DECIMAL(10, 2)) AS 'Total Revenue'
FROM pizzas p
JOIN order_details od 
	ON p.pizza_id = od.pizza_id;


-- 2. We want to know which pizzas are performing well and which aren’t. Break down
-- sales performance by type, size, and category.
SELECT p.pizza_type_id,
	   pt.name, 
	   p.size, 
	   pt.category,
	   SUM(od.quantity) AS Total_Quantity_Sold,
	   CAST(SUM(p.price * od.quantity) AS DECIMAL(10, 2)) AS Total_Revenue
FROM pizza_types pt
JOIN pizzas p 
	ON p.pizza_type_id = pt.pizza_type_id
JOIN order_details od 
	ON od.pizza_id = p.pizza_id
GROUP BY p.pizza_type_id, 
		 pt.name, 
		 p.size, 
		 pt.category
ORDER BY Total_Revenue DESC;


-- 3. Which pizza type, size, and category generate the highest and lowest revenue?
WITH pizza_info AS 
            (
                SELECT p.pizza_type_id,
                       pt.name,
                       p.size, 
                       pt.category,
                       CAST(SUM(p.price * od.quantity) AS DECIMAL(10, 2)) AS Total_Revenue
                FROM pizza_types pt
                JOIN pizzas p 
                    ON p.pizza_type_id = pt.pizza_type_id
                JOIN order_details od 
                    ON od.pizza_id = p.pizza_id
                GROUP BY p.pizza_type_id,  
                            pt.name,
                            p.size, 
                            pt.category
			) 
SELECT pizza_type_id,
	   name,
       size,
       category,
	   Total_Revenue,
       CASE
            WHEN Highest_Revenue = 1 THEN 'High Revenue'
            WHEN Lowest_Revenue = 1 THEN 'Low Revenue'
       END AS Revenue_Rank
FROM (
		SELECT *,
			RANK() OVER(ORDER BY Total_Revenue DESC) AS Highest_Revenue, 
			RANK() OVER(ORDER BY Total_Revenue ASC) AS Lowest_Revenue
FROM pizza_info
	 ) AS ranks
WHERE Highest_Revenue = 1 
	  OR Lowest_Revenue = 1;


-- 4. Identify the top-performing and underperforming pizzas to evaluate potential menu adjustments.
WITH pizza_performance AS
            (
                SELECT
                    p.pizza_type_id,
                    pt.name,
                    p.size,
                    pt.category,
                    SUM(od.quantity) AS Total_Quantity_Sold,
                    CAST(SUM(p.price * od.quantity) AS DECIMAL(10,2)) AS Total_Revenue
                FROM pizza_types pt
                JOIN pizzas p
                    ON pt.pizza_type_id = p.pizza_type_id
                JOIN order_details od
                    ON p.pizza_id = od.pizza_id
                GROUP BY
                    p.pizza_type_id,
                    pt.name,
                    p.size,
                    pt.category
            ),
Ranked_Pizzas AS
    (
    SELECT *,
           RANK() OVER(ORDER BY Total_Revenue DESC) AS Top_Rank,
           RANK() OVER(ORDER BY Total_Revenue ASC) AS Bottom_Rank
    FROM pizza_performance
    )
SELECT
    pizza_type_id,
    name,
    size,
    category,
    Total_Quantity_Sold,
    Total_Revenue,
    CASE
        WHEN Top_Rank <= 5 THEN 'Top Performing'
        WHEN Bottom_Rank <= 5 THEN 'Underperforming'
    END AS Performance
FROM Ranked_Pizzas
WHERE Top_Rank <= 5
   OR Bottom_Rank <= 5
ORDER BY Total_Revenue DESC;


-- 5. What are the top 5 pizzas by quantity sold?
SELECT TOP 5
    p.pizza_type_id,
    pt.name,
    p.size,
    pt.category,
    SUM(od.quantity) AS Total_Quantity_Sold
FROM order_details od
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
GROUP BY
    p.pizza_type_id,
    pt.name,
    p.size,
    pt.category
ORDER BY Total_Quantity_Sold DESC;


-- 6. What is the revenue contribution of each pizza size (e.g. small, medium, large)?
SELECT
    p.size,
    CAST(SUM(p.price * od.quantity) AS DECIMAL(10,2)) AS Total_Revenue,
    CAST(
        SUM(p.price * od.quantity) * 100.0 /
        SUM(SUM(p.price * od.quantity)) OVER () AS DECIMAL(5,2)
    ) AS Revenue_Contribution_Percentage
FROM pizzas p
JOIN order_details od
    ON p.pizza_id = od.pizza_id
GROUP BY p.size
ORDER BY Total_Revenue DESC;


-- 7. What is the revenue contribution of each category (e.g., vegetarian vs. nonvegetarian)?
SELECT
    pt.category,
    CAST(SUM(p.price * od.quantity) AS DECIMAL(10,2)) AS Total_Revenue,
    CAST(
        SUM(p.price * od.quantity) * 100.0 /
        SUM(SUM(p.price * od.quantity)) OVER () AS DECIMAL(5,2)
    ) AS Revenue_Contribution_Percentage
FROM pizzas p
JOIN order_details od
    ON p.pizza_id = od.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.category
ORDER BY Total_Revenue DESC;


-- 8. Provide insights into revenue trends across different time periods (e.g. daily, weekly, monthly).
-- Daily Revenue Trends 
SELECT o.date,
       CAST(SUM(p.price * od.quantity) AS DECIMAL(10, 2)) Total_Revenue
FROM orders o
JOIN order_details od 
    ON od.order_id = o.order_id
JOIN pizzas p 
    ON  p.pizza_id = od.pizza_id
GROUP BY o.date
ORDER BY o.date;

-- Weekly Revenue Trends 
SELECT DATEPART(WEEK, o.date) AS Week_Num,
       CAST(SUM(p.price * od.quantity) AS DECIMAL(10, 2)) Total_Revenue
FROM orders o
JOIN order_details od 
    ON od.order_id = o.order_id
JOIN pizzas p 
    ON  p.pizza_id = od.pizza_id
GROUP BY DATEPART(WEEK, o.date)
ORDER BY Week_Num;

-- Monthly Revenue Trends 
SELECT DATEPART(MONTH, o.date) AS Month_Num,
       CAST(SUM(p.price * od.quantity) AS DECIMAL(10, 2)) Total_Revenue
FROM orders o
JOIN order_details od 
    ON od.order_id = o.order_id
JOIN pizzas p 
    ON  p.pizza_id = od.pizza_id
GROUP BY DATEPART(MONTH, o.date)
ORDER BY Month_Num;

-- Yearly Revenue Trends 
SELECT DATEPART(YEAR, o.date) AS Year_Num,
       CAST(SUM(p.price * od.quantity) AS DECIMAL(10, 2)) Total_Revenue
FROM orders o
JOIN order_details od 
    ON od.order_id = o.order_id
JOIN pizzas p 
    ON  p.pizza_id = od.pizza_id
GROUP BY DATEPART(YEAR, o.date)
ORDER BY Year_Num;


-- 9. What is the average monthly revenue, and how does it vary by category?
WITH Average_Monthly_Revenue AS
(
    SELECT
        YEAR(o.date) AS Order_Year,
        MONTH(o.date) AS Order_Month,
        pt.category,
        SUM(p.price * od.quantity) AS Monthly_Revenue
    FROM pizza_types pt
    JOIN pizzas p
        ON pt.pizza_type_id = p.pizza_type_id
    JOIN order_details od
        ON od.pizza_id = p.pizza_id
    JOIN orders o
        ON od.order_id = o.order_id
    GROUP BY
        YEAR(o.date),
        MONTH(o.date),
        pt.category
)
SELECT
    Order_Month,
    CAST(AVG(CASE WHEN category = 'Chicken' THEN Monthly_Revenue END) AS DECIMAL(10,2)) AS Chicken,
    CAST(AVG(CASE WHEN category = 'Classic' THEN Monthly_Revenue END) AS DECIMAL(10,2)) AS Classic,
    CAST(AVG(CASE WHEN category = 'Supreme' THEN Monthly_Revenue END) AS DECIMAL(10,2)) AS Supreme,
    CAST(AVG(CASE WHEN category = 'Veggie' THEN Monthly_Revenue END) AS DECIMAL(10,2)) AS Veggie
FROM Average_Monthly_Revenue
GROUP BY Order_Month
ORDER BY Order_Month;


WITH Category_Monthly_Revenue AS
(
    SELECT
        YEAR(o.date) AS Order_Year,
        MONTH(o.date) AS Order_Month,
        pt.category,
        CAST(SUM(p.price * od.quantity) AS DECIMAL(10, 2)) AS Monthly_Revenue
    FROM pizza_types pt
    JOIN pizzas p
        ON pt.pizza_type_id = p.pizza_type_id
    JOIN order_details od
        ON od.pizza_id = p.pizza_id
    JOIN orders o
        ON od.order_id = o.order_id
    GROUP BY
        YEAR(o.date),
        MONTH(o.date),
        pt.category
),
Average_Monthly_Revenue AS
(
    SELECT
        Order_Month,
        category,
        CAST(AVG(Monthly_Revenue) AS DECIMAL(10, 2)) AS Average_Monthly_Revenue
    FROM Category_Monthly_Revenue
    GROUP BY
        Order_Month,
        category
)
SELECT *
FROM
(
    SELECT
        Order_Month,
        category,
        CAST(Average_Monthly_Revenue AS DECIMAL(10,2)) AS Average_Monthly_Revenue
    FROM Average_Monthly_Revenue
) AS SourceTable
PIVOT
(
    AVG(Average_Monthly_Revenue)
    FOR category IN ([Chicken], [Classic], [Supreme], [Veggie])
) AS PivotTable
ORDER BY Order_Month;


-- 10. Which pizzas are performing poorly?
SELECT TOP 5 
        p.pizza_id, 
        pt.name, 
        p.size,
        pt.category,
        SUM(od.quantity) AS Total_Quantity_Sold,
        CAST(SUM(p.price * od.quantity) AS DECIMAL(10, 2)) AS Total_Revenue
FROM pizzas p
JOIN order_details od 
        ON p.pizza_id = od.pizza_id
JOIN pizza_types pt 
        ON pt.pizza_type_id = p.pizza_type_id
GROUP BY 
        p.pizza_id, 
        pt.name,
        p.size,
        pt.category
ORDER BY Total_Revenue ASC;


-- Customer Behavior
-- 11.Can we identify any trends in customer ordering behavior?
-- Orders by Day of Week 
SELECT
    DATEPART(WEEKDAY, date) AS Day_Number,
    DATENAME(WEEKDAY, date) AS Day_Name, 
    COUNT(order_id) AS Total_Orders
FROM orders
GROUP BY DATENAME(WEEKDAY, date),
         DATEPART(WEEKDAY, date)
ORDER BY DATEPART(WEEKDAY, date);

-- Orders by Hour (Peak Ordering Hours)
SELECT
    DATEPART(HOUR, time) AS Order_Hour,
    COUNT(order_id) AS Total_Orders
FROM orders
GROUP BY DATEPART(HOUR, time)
ORDER BY Order_Hour ;

-- Average Order Value
WITH Order_Revenue AS
(
    SELECT
        o.order_id,
        SUM(p.price * od.quantity) AS Order_Value
    FROM orders o
    JOIN order_details od
        ON o.order_id = od.order_id
    JOIN pizzas p
        ON od.pizza_id = p.pizza_id
    GROUP BY o.order_id
)
SELECT
    CAST(AVG(Order_Value) AS DECIMAL(10,2)) AS Average_Order_Value
FROM Order_Revenue;

-- Average Pizzas per Order
SELECT
    CAST(AVG(Total_Items) AS DECIMAL(10,2)) AS Average_Pizzas_Per_Order
FROM
(
    SELECT
        order_id,
        SUM(quantity) AS Total_Items
    FROM order_details
    GROUP BY order_id
) t;

-- Large vs Small Orders
SELECT
    CASE
        WHEN Total_Items <= 2 THEN 'Small Order'
        WHEN Total_Items BETWEEN 3 AND 5 THEN 'Medium Order'
        ELSE 'Large Order'
    END AS Order_Size,
    COUNT(*) AS Number_of_Orders
FROM
(
    SELECT
        order_id,
        SUM(quantity) AS Total_Items
    FROM order_details
    GROUP BY order_id
) t
GROUP BY
    CASE
        WHEN Total_Items <= 2 THEN 'Small Order'
        WHEN Total_Items BETWEEN 3 AND 5 THEN 'Medium Order'
        ELSE 'Large Order'
    END;

-- Weekday vs Weekend Orders
SELECT
    CASE
        WHEN DATENAME(WEEKDAY, date) IN ('Saturday','Sunday')
            THEN 'Weekend'
        ELSE 'Weekday'
    END AS Order_Type,
    COUNT(*) AS Total_Orders
FROM orders
GROUP BY
    CASE
        WHEN DATENAME(WEEKDAY, date) IN ('Saturday','Sunday')
            THEN 'Weekend'
        ELSE 'Weekday'
    END;


-- 12. Analyze the average order size and revenue per order.
WITH OrderSummary AS
(
    SELECT
        od.order_id,
        SUM(p.price * od.quantity) AS Revenue_Per_Order,
        SUM(od.quantity) AS Order_Size
    FROM order_details od
    JOIN pizzas p
        ON od.pizza_id = p.pizza_id
    GROUP BY od.order_id
)
SELECT order_id,
    CAST(AVG(Revenue_Per_Order) AS DECIMAL(10,2)) AS Average_Revenue_Per_Order,
    CAST(AVG(Order_Size) AS DECIMAL(10,2)) AS Average_Order_Size
FROM OrderSummary
GROUP BY order_id;


-- 13. What is the average number of pizzas sold per order?
WITH Average_Pizzas AS(
SELECT od.order_id, SUM(od.quantity) AS Total_Pizzas
FROM order_details od
JOIN pizzas p 
    ON p.pizza_id = od.pizza_id
GROUP BY od.order_id)
SELECT order_id, CAST(AVG(Total_Pizzas) AS DECIMAL(10, 2))AS Average_Pizzas_Per_Order
FROM Average_Pizzas
GROUP BY order_id;


-- 14. Identify popular pizza combinations often ordered together.
SELECT
    pt1.name AS Pizza_1,
    pt2.name AS Pizza_2,
    COUNT(*) AS Times_Ordered_Together
FROM order_details od1
JOIN order_details od2
    ON od1.order_id = od2.order_id
   AND od1.pizza_id < od2.pizza_id
JOIN pizzas p1
    ON od1.pizza_id = p1.pizza_id
JOIN pizzas p2
    ON od2.pizza_id = p2.pizza_id
JOIN pizza_types pt1
    ON p1.pizza_type_id = pt1.pizza_type_id
JOIN pizza_types pt2
    ON p2.pizza_type_id = pt2.pizza_type_id
GROUP BY
    pt1.name,
    pt2.name
ORDER BY
    Times_Ordered_Together DESC;


-- 15. How many unique orders contained only vegetarian pizzas?
SELECT pt.pizza_type_id, COUNT(DISTINCT(od.order_id)) AS Unique_Orders
FROM pizza_types pt
JOIN pizzas p 
    ON p.pizza_type_id = pt.pizza_type_id
JOIN order_details od 
    ON od.pizza_id = p.pizza_id
WHERE pt.category = 'Veggie'
GROUP BY pt.pizza_type_id
ORDER BY Unique_Orders DESC;

SELECT
    COUNT(*) AS Unique_Veggie_Orders
FROM (
    SELECT
        od.order_id
    FROM order_details od
    JOIN pizzas p
        ON od.pizza_id = p.pizza_id
    JOIN pizza_types pt
        ON p.pizza_type_id = pt.pizza_type_id
    GROUP BY od.order_id
    HAVING COUNT(CASE WHEN pt.category <> 'Veggie' THEN 1 END) = 0
) AS VeggieOrders;

-- 16. Which size of pizza is most popular among customers?
SELECT p.size, SUM(od.quantity) AS Total_Orders
FROM pizzas p
JOIN order_details od 
    ON p.pizza_id = od.pizza_id
GROUP BY p.size
ORDER BY Total_Orders;

-- 17. How does customer behavior vary during weekends compared to weekdays?
SELECT
    CASE
        WHEN DATENAME(WEEKDAY, o.date) IN ('Saturday', 'Sunday')
            THEN 'Weekend'
        ELSE 'Weekday'
    END AS Day_Type,
    COUNT(DISTINCT o.order_id) AS Total_Orders,
    SUM(od.quantity) AS Total_Pizzas_Sold,
    ROUND(AVG(CAST(od.quantity AS FLOAT)), 2) AS Avg_Pizzas_Per_Item
FROM orders o
JOIN order_details od
    ON o.order_id = od.order_id
GROUP BY
    CASE
        WHEN DATENAME(WEEKDAY, o.date) IN ('Saturday', 'Sunday')
            THEN 'Weekend'
        ELSE 'Weekday'
    END;


-- 18. What is the revenue breakdown by pizza type for orders placed during weekends?
SELECT
    pt.name AS Pizza_Name,
    CAST(SUM(p.price * od.quantity) AS DECIMAL(10,2)) AS Revenue
FROM orders o
JOIN order_details od
    ON o.order_id = od.order_id
JOIN pizzas p
    ON p.pizza_id = od.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
WHERE DATENAME(WEEKDAY, o.date) IN ('Saturday', 'Sunday')
GROUP BY pt.name
ORDER BY Revenue DESC;


-- 19. When do customers place the most orders (hour of the day, day of the week)?
SELECT TOP 5
    DATENAME(WEEKDAY, o.date) AS Day_Of_Week,
    DATEPART(HOUR, o.time) AS Order_Hour,
    COUNT(DISTINCT o.order_id) AS Total_Orders
FROM orders o
GROUP BY
    DATENAME(WEEKDAY, o.date),
    DATEPART(HOUR, o.time)
ORDER BY Total_Orders DESC;


-- 20.Determine peak ordering times and customer preferences for pizza size, type, and category.
SELECT TOP 1
    DATEPART(HOUR, o.time) AS Peak_Hour,
    p.size,
    pt.name,
    pt.pizza_type_id,
    pt.category,
    COUNT(DISTINCT o.order_id) AS Total_Orders
FROM orders o
JOIN order_details od
    ON o.order_id = od.order_id
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
GROUP BY
    DATEPART(HOUR, o.time),
    p.size,
    pt.name,
    pt.pizza_type_id,
    pt.category
ORDER BY Total_Orders DESC;

-- Peak Ordering Time
SELECT TOP 1
    DATEPART(HOUR, time) AS Peak_Hour,
    COUNT(*) AS Total_Orders
FROM orders
GROUP BY DATEPART(HOUR, time)
ORDER BY Total_Orders DESC;

-- Favorite Pizza Size
SELECT TOP 1
    p.size,
    SUM(od.quantity) AS Total_Pizzas_Sold
FROM order_details od
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
GROUP BY p.size
ORDER BY Total_Pizzas_Sold DESC;

-- Favorite Pizza Type
SELECT TOP 1
    pt.name,
    SUM(od.quantity) AS Total_Pizzas_Sold
FROM order_details od
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.name
ORDER BY Total_Pizzas_Sold DESC;

-- Favorite Category
SELECT TOP 1
    pt.category,
    SUM(od.quantity) AS Total_Pizzas_Sold
FROM order_details od
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.category
ORDER BY Total_Pizzas_Sold DESC;


-- 21. What is the average quantity of pizzas per order during the peak sales hours?
WITH OrderSummary AS
(
    SELECT
        o.order_id,
        DATEPART(HOUR, o.time) AS Sales_Hour,
        SUM(od.quantity) AS Pizzas_Per_Order
    FROM orders o
    JOIN order_details od
        ON o.order_id = od.order_id
    GROUP BY
        o.order_id,
        DATEPART(HOUR, o.time)
)
SELECT TOP 1
    Sales_Hour,
    COUNT(*) AS Total_Orders,
    ROUND(AVG(CAST(Pizzas_Per_Order AS FLOAT)), 2) AS Avg_Pizzas_Per_Order
FROM OrderSummary
GROUP BY Sales_Hour
ORDER BY Total_Orders DESC;



-- Operational Insights
-- 22. How many pizzas are sold each month, and what is the trend over time?
SELECT
    DATENAME(MONTH, o.date) AS Month_Name,
    MONTH(o.date) AS Month_No,
    SUM(od.quantity) AS Pizzas_Sold
FROM orders o
JOIN order_details od
    ON o.order_id = od.order_id
GROUP BY
    DATENAME(MONTH, o.date),
    MONTH(o.date)
ORDER BY Month_No;


-- 23. What are the total quantities of each pizza type sold?
SELECT
    pt.name AS Pizza_Type,
    p.pizza_type_id,
    SUM(od.quantity) AS Total_Pizzas_Sold
FROM order_details od
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
GROUP BY
    pt.name,
    p.pizza_type_id
ORDER BY Total_Pizzas_Sold DESC;


-- 24. How much of each ingredient is required to meet the sales demand?
SELECT
    LTRIM(RTRIM(s.value)) AS Ingredient,
    SUM(od.quantity) AS Total_Required
FROM pizza_types pt
JOIN pizzas p
    ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od
    ON p.pizza_id = od.pizza_id
CROSS APPLY STRING_SPLIT(pt.ingredients, ',') s
GROUP BY
    LTRIM(RTRIM(s.value))
ORDER BY Total_Required DESC;


-- 25. Which ingredients are the most and least utilized based on current trends?
WITH IngredientUsage AS
(
    SELECT
        LTRIM(RTRIM(i.value)) AS Ingredient,
        SUM(od.quantity) AS Total_Required
    FROM pizza_types pt
    JOIN pizzas p
        ON pt.pizza_type_id = p.pizza_type_id
    JOIN order_details od
        ON p.pizza_id = od.pizza_id
    CROSS APPLY STRING_SPLIT(pt.ingredients, ',') AS i
    GROUP BY LTRIM(RTRIM(i.value))
)
SELECT *
FROM
(
    SELECT TOP 2
        Ingredient,
        Total_Required,
        'Most Utilized' AS Utilization
    FROM IngredientUsage
    ORDER BY Total_Required DESC
) AS MostUsed

UNION ALL

SELECT *
FROM
(
    SELECT TOP 2
        Ingredient,
        Total_Required,
        'Least Utilized' AS Utilization
    FROM IngredientUsage
    ORDER BY Total_Required ASC
) AS LeastUsed;


-- 26. What are the monthly requirements for the top 3 most used ingredients?
WITH TopIngredients AS
(
    SELECT TOP 3
        LTRIM(RTRIM(s.value)) AS Ingredient
    FROM pizza_types pt
    JOIN pizzas p
        ON pt.pizza_type_id = p.pizza_type_id
    JOIN order_details od
        ON p.pizza_id = od.pizza_id
    CROSS APPLY STRING_SPLIT(pt.ingredients, ',') s
    GROUP BY LTRIM(RTRIM(s.value))
    ORDER BY SUM(od.quantity) DESC
)

SELECT
    LTRIM(RTRIM(s.value)) AS Ingredient,
    DATENAME(MONTH, o.date) AS Month_Name,
    MONTH(o.date) AS Month_No,
    SUM(od.quantity) AS Total_Required
FROM pizza_types pt
JOIN pizzas p
    ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od
    ON p.pizza_id = od.pizza_id
JOIN orders o
    ON o.order_id = od.order_id
CROSS APPLY STRING_SPLIT(pt.ingredients, ',') s
WHERE LTRIM(RTRIM(s.value)) IN
(
    SELECT Ingredient
    FROM TopIngredients
)
GROUP BY
    LTRIM(RTRIM(s.value)),
    DATENAME(MONTH, o.date),
    MONTH(o.date)
ORDER BY
    Ingredient,
    Month_No;


-- 27. Help us optimize our ingredient supply chain. Which ingredients are used most frequently, and what are the monthly requirements?
WITH IngredientUsage AS
(
    SELECT
        LTRIM(RTRIM(s.value)) AS Ingredient,
        SUM(od.quantity) AS Total_Used
    FROM pizza_types pt
    JOIN pizzas p
        ON pt.pizza_type_id = p.pizza_type_id
    JOIN order_details od
        ON p.pizza_id = od.pizza_id
    CROSS APPLY STRING_SPLIT(pt.ingredients, ',') s
    GROUP BY LTRIM(RTRIM(s.value))
),

TopIngredients AS
(
    SELECT TOP 10
        Ingredient
    FROM IngredientUsage
    ORDER BY Total_Used DESC
)

SELECT
    LTRIM(RTRIM(s.value)) AS Ingredient,
    DATENAME(MONTH, o.date) AS Month_Name,
    MONTH(o.date) AS Month_No,
    SUM(od.quantity) AS Monthly_Requirement
FROM pizza_types pt
JOIN pizzas p
    ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od
    ON p.pizza_id = od.pizza_id
JOIN orders o
    ON o.order_id = od.order_id
CROSS APPLY STRING_SPLIT(pt.ingredients, ',') s
WHERE LTRIM(RTRIM(s.value)) IN 
(
    SELECT Ingredient
    FROM TopIngredients
)
GROUP BY
    LTRIM(RTRIM(s.value)),
    DATENAME(MONTH, o.date),
    MONTH(o.date)
ORDER BY
    Ingredient,
    Month_No;


-- 28. Provide insights into high-demand periods where operational adjustments may be required.
-- 1: Peak Hours
SELECT
    DATEPART(HOUR, o.time) AS Order_Hour,
    COUNT(DISTINCT o.order_id) AS Total_Orders,
    SUM(od.quantity) AS Total_Pizzas_Sold
FROM orders o
JOIN order_details od
    ON o.order_id = od.order_id
GROUP BY DATEPART(HOUR, o.time)
ORDER BY Total_Orders DESC;

-- Peak Days
SELECT
    DATENAME(WEEKDAY, o.date) AS Day_Name,
    COUNT(DISTINCT o.order_id) AS Total_Orders,
    SUM(od.quantity) AS Total_Pizzas_Sold
FROM orders o
JOIN order_details od
    ON o.order_id = od.order_id
GROUP BY DATENAME(WEEKDAY, o.date)
ORDER BY Total_Orders DESC;

-- Monthly Demand
SELECT
    DATENAME(MONTH, o.date) AS Month_Name,
    MONTH(o.date) AS Month_No,
    COUNT(DISTINCT o.order_id) AS Total_Orders,
    SUM(od.quantity) AS Total_Pizzas_Sold
FROM orders o
JOIN order_details od
    ON o.order_id = od.order_id
GROUP BY
    DATENAME(MONTH, o.date),
    MONTH(o.date)
ORDER BY Month_No;


-- 29. Suggest ways to improve efficiency based on trends in pizza preparation and delivery.
-- Most Ordered Pizza Types
SELECT
    pt.name,
    SUM(od.quantity) AS Total_Sold
FROM order_details od
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.name
ORDER BY Total_Sold DESC;

-- Most Used Ingredients
SELECT
    LTRIM(RTRIM(s.value)) AS Ingredient,
    SUM(od.quantity) AS Total_Required
FROM pizza_types pt
JOIN pizzas p
    ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od
    ON p.pizza_id = od.pizza_id
CROSS APPLY STRING_SPLIT(pt.ingredients, ',') AS s
GROUP BY LTRIM(RTRIM(s.value))
ORDER BY Total_Required DESC;

-- Peak Hour + Pizza Preference
SELECT
    DATEPART(HOUR, o.time) AS Peak_Hour,
    pt.name,
    SUM(od.quantity) AS Total_Sold
FROM orders o
JOIN order_details od
    ON o.order_id = od.order_id
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
GROUP BY
    DATEPART(HOUR, o.time),
    pt.name
ORDER BY
    Peak_Hour,
    Total_Sold DESC;


-- Strategic Decisions
-- 30. Are there pizzas that consistently generate low sales, and what action should we take regarding them?
SELECT TOP 5
    pt.name AS Pizza_Name,
    pt.category,
    SUM(od.quantity) AS Total_Pizzas_Sold,
    CAST(SUM(p.price * od.quantity) AS DECIMAL(10,2)) AS Revenue
FROM order_details od
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
GROUP BY
    pt.name,
    pt.category
ORDER BY Total_Pizzas_Sold ASC;


-- 31. How can we optimize inventory management to minimize waste and maximize efficiency?
SELECT
    LTRIM(RTRIM(s.value)) AS Ingredient,
    SUM(od.quantity) AS Total_Required
FROM pizza_types pt
JOIN pizzas p
    ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od
    ON p.pizza_id = od.pizza_id
CROSS APPLY STRING_SPLIT(pt.ingredients, ',') AS s
GROUP BY
    LTRIM(RTRIM(s.value))
ORDER BY Total_Required DESC;


-- 32. The company is considering expanding its vegetarian pizza line. Does the data support this decision?
SELECT
    pt.category,
    COUNT(DISTINCT od.order_id) AS Total_Orders,
    SUM(od.quantity) AS Total_Pizzas_Sold,
    CAST(SUM(p.price * od.quantity) AS DECIMAL(10,2)) AS Revenue
FROM pizza_types pt
JOIN pizzas p
    ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od
    ON p.pizza_id = od.pizza_id
GROUP BY pt.category
ORDER BY Revenue DESC;


-- 33. Is there an opportunity to introduce a new pizza size or category based on sales trends?
SELECT
    p.size,
    SUM(od.quantity) AS Total_Sold,
    CAST(SUM(p.price * od.quantity) AS DECIMAL(10,2)) AS Revenue
FROM pizzas p
JOIN order_details od
    ON p.pizza_id = od.pizza_id
GROUP BY p.size
ORDER BY Total_Sold DESC;


-- 34. Are there patterns suggesting the need for a new ingredient combination?
SELECT
    pt.ingredients,
    SUM(od.quantity) AS Total_Sold
FROM pizza_types pt
JOIN pizzas p
    ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od
    ON p.pizza_id = od.pizza_id
GROUP BY pt.ingredients
ORDER BY Total_Sold DESC;


-- 35. Should we introduce a ‘family-size’ pizza to increase revenue? Use the data to justify your recommendation.
SELECT
    p.size,
    COUNT(DISTINCT od.order_id) AS Total_Orders,
    SUM(od.quantity) AS Total_Pizzas_Sold,
    CAST(SUM(p.price * od.quantity) AS DECIMAL(10,2)) AS Revenue
FROM pizzas p
JOIN order_details od
    ON p.pizza_id = od.pizza_id
GROUP BY p.size
ORDER BY Revenue DESC;


-- 36. Based on ingredient usage, should we negotiate better pricing with suppliers for high-demand ingredients?
SELECT
    LTRIM(RTRIM(s.value)) AS Ingredient,
    SUM(od.quantity) AS Total_Required
FROM pizza_types pt
JOIN pizzas p
    ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od
    ON p.pizza_id = od.pizza_id
CROSS APPLY STRING_SPLIT(pt.ingredients, ',') AS s
GROUP BY
    LTRIM(RTRIM(s.value))
ORDER BY Total_Required DESC;

-- Last Minute Request
-- We need a quick summary of top-performing pizzas by revenue and size for tomorrow’s board meeting!
SELECT TOP 10
    pt.name AS Pizza_Name,
    p.size,
    SUM(od.quantity) AS Total_Quantity_Sold,
    CAST(SUM(od.quantity * p.price) AS DECIMAL(10,2)) AS Total_Revenue
FROM order_details od
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
GROUP BY
    pt.name,
    p.size
ORDER BY
    Total_Revenue DESC;


-- Provide a quick list of the top 3 least-performing pizzas by category and size.
SELECT TOP 3
    pt.category,
    pt.name AS Pizza_Name,
    p.size,
    SUM(od.quantity) AS Total_Quantity_Sold,
    CAST(SUM(od.quantity * p.price) AS DECIMAL(10,2)) AS Total_Revenue
FROM order_details od
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
GROUP BY
    pt.category,
    pt.name,
    p.size
ORDER BY
    Total_Revenue ASC;

-- Can we get a count of orders that were placed during weekends vs weekdays to discuss operational adjustments?
SELECT
    CASE
        WHEN DATENAME(WEEKDAY, o.date) IN ('Saturday','Sunday')
        THEN 'Weekend'
        ELSE 'Weekday'
    END AS Day_Type,
    COUNT(DISTINCT o.order_id) AS Total_Orders
FROM orders o
GROUP BY
    CASE
        WHEN DATENAME(WEEKDAY, o.date) IN ('Saturday','Sunday')
        THEN 'Weekend'
        ELSE 'Weekday'
    END;


-- Generate a summary of peak order times for each day of the week for scheduling staff shifts more effectively.
WITH HourlyOrders AS
(
    SELECT
        DATENAME(WEEKDAY, date) AS Day_Name,
        DATEPART(HOUR, time) AS Order_Hour,
        COUNT(*) AS Total_Orders
    FROM orders
    GROUP BY
        DATENAME(WEEKDAY, date),
        DATEPART(HOUR, time)
),
RankedHours AS
(
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY Day_Name ORDER BY Total_Orders DESC) AS rn
    FROM HourlyOrders
)
SELECT
    Day_Name,
    Order_Hour,
    Total_Orders
FROM RankedHours
WHERE rn = 1
ORDER BY
CASE Day_Name
    WHEN 'Monday' THEN 1
    WHEN 'Tuesday' THEN 2
    WHEN 'Wednesday' THEN 3
    WHEN 'Thursday' THEN 4
    WHEN 'Friday' THEN 5
    WHEN 'Saturday' THEN 6
    WHEN 'Sunday' THEN 7
END;


-- Budgeting Constraints
-- What if we could only promote three pizzas—how would you decide which ones?
SELECT TOP 3
    pt.name AS Pizza_Name,
    SUM(od.quantity) AS Quantity_Sold,
    CAST(SUM(od.quantity * p.price) AS DECIMAL(10,2)) AS Revenue
FROM order_details od
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.name
ORDER BY
    Revenue DESC,
    Quantity_Sold DESC;


-- Assume the company needs to reduce costs by 10% on ingredient procurement.
WITH IngredientUsage AS
(
    SELECT
        TRIM(value) AS Ingredient,
        SUM(od.quantity) AS Total_Usage
    FROM pizza_types pt
    JOIN pizzas p
        ON pt.pizza_type_id = p.pizza_type_id
    JOIN order_details od
        ON p.pizza_id = od.pizza_id
    CROSS APPLY STRING_SPLIT(pt.ingredients, ',')
    GROUP BY
        TRIM(value)
)

SELECT TOP 10
    Ingredient,
    Total_Usage,
    CAST(
        Total_Usage * 100.0 /
        SUM(Total_Usage) OVER ()
        AS DECIMAL(5,2)
    ) AS Usage_Percentage
FROM IngredientUsage
ORDER BY Total_Usage DESC;

-- Which ingredients should be prioritized, and why?
SELECT
    TRIM(value) AS Ingredient,
    SUM(od.quantity) AS Usage_Count
FROM order_details od
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
CROSS APPLY STRING_SPLIT(pt.ingredients, ',')
GROUP BY
    TRIM(value)
ORDER BY
    Usage_Count DESC;


-- If we can only run a promotional offer on one size of pizza, which size should it be based on current trends?
SELECT
    p.size,
    SUM(od.quantity) AS Quantity_Sold,
    CAST(SUM(od.quantity * p.price) AS DECIMAL(10,2)) AS Revenue
FROM order_details od
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
GROUP BY
    p.size
ORDER BY
    Revenue DESC;


-- What if we had to discontinue one pizza category due to rising costs? Suggest the least impactful category.
SELECT
    pt.category,
    SUM(od.quantity) AS Quantity_Sold,
    CAST(SUM(od.quantity * p.price) AS DECIMAL(10,2)) AS Revenue
FROM order_details od
JOIN pizzas p
    ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
GROUP BY
    pt.category
ORDER BY
    Revenue ASC;